{
  imports = [
    ./boot.nix
    ./environment.nix
    ./file-systems.nix
    ./gnome.nix
    ./hardware.nix
    ./i18n.nix
    ./networking.nix
    ./nix.nix
    ./power-management.nix
    ./programs.nix
    ./qt5.nix
    ./security.nix
    ./services.nix
    ./users.nix
    ./virtualisation.nix
  ];
}
