name: Build ISO

on:
  push:

jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - machine: swift3
            hostname: SF314-52
          - machine: zx4250
            hostname: ZX4250
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Install jq
        run: nix profile install nixpkgs#jq

      - name: Build ISO
        run: |
          echo "OUT_PATH=$(nix build --print-build-logs --json .#${{ matrix.machine }}-iso | jq -r '.[0].outputs.out')" >> $GITHUB_ENV

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: nixos-${{ matrix.hostname }}.iso
          path: ${{ env.OUT_PATH }}
